export type Country = 'usa' | 'canada' | 'mexico'

export type Plate = {
  name: string
  abbr?: string
}

export const plates = {
  usa: [
    { name: 'Alabama', abbr: 'AL' },
    { name: 'Alaska', abbr: 'AK' },
    { name: 'Arizona', abbr: 'AZ' },
    { name: 'Arkansas', abbr: 'AR' },
    { name: 'California', abbr: 'CA' },
    { name: 'Colorado', abbr: 'CO' },
    { name: 'Connecticut', abbr: 'CT' },
    { name: 'Delaware', abbr: 'DE' },
    { name: 'Florida', abbr: 'FL' },
    { name: 'Georgia', abbr: 'GA' },
    { name: 'Hawaii', abbr: 'HI' },
    { name: 'Idaho', abbr: 'ID' },
    { name: 'Illinois', abbr: 'IL' },
    { name: 'Indiana', abbr: 'IN' },
    { name: 'Iowa', abbr: 'IA' },
    { name: 'Kansas', abbr: 'KS' },
    { name: 'Kentucky', abbr: 'KY' },
    { name: 'Louisiana', abbr: 'LA' },
    { name: 'Maine', abbr: 'ME' },
    { name: 'Maryland', abbr: 'MD' },
    { name: 'Massachusetts', abbr: 'MA' },
    { name: 'Michigan', abbr: 'MI' },
    { name: 'Minnesota', abbr: 'MN' },
    { name: 'Mississippi', abbr: 'MS' },
    { name: 'Missouri', abbr: 'MO' },
    { name: 'Montana', abbr: 'MT' },
    { name: 'Nebraska', abbr: 'NE' },
    { name: 'Nevada', abbr: 'NV' },
    { name: 'New Hampshire', abbr: 'NH' },
    { name: 'New Jersey', abbr: 'NJ' },
    { name: 'New Mexico', abbr: 'NM' },
    { name: 'New York', abbr: 'NY' },
    { name: 'North Carolina', abbr: 'NC' },
    { name: 'North Dakota', abbr: 'ND' },
    { name: 'Ohio', abbr: 'OH' },
    { name: 'Oklahoma', abbr: 'OK' },
    { name: 'Oregon', abbr: 'OR' },
    { name: 'Pennsylvania', abbr: 'PA' },
    { name: 'Rhode Island', abbr: 'RI' },
    { name: 'South Carolina', abbr: 'SC' },
    { name: 'South Dakota', abbr: 'SD' },
    { name: 'Tennessee', abbr: 'TN' },
    { name: 'Texas', abbr: 'TX' },
    { name: 'Utah', abbr: 'UT' },
    { name: 'Vermont', abbr: 'VT' },
    { name: 'Virginia', abbr: 'VA' },
    { name: 'Washington', abbr: 'WA' },
    { name: 'West Virginia', abbr: 'WV' },
    { name: 'Wisconsin', abbr: 'WI' },
    { name: 'Wyoming', abbr: 'WY' },
  ],
  canada: [
    { name: 'Nunavut' },
    { name: 'Quebec' },
    { name: 'Northwest Territories' },
    { name: 'Ontario' },
    { name: 'British Columbia' },
    { name: 'Alberta' },
    { name: 'Saskatchewan' },
    { name: 'Manitoba' },
    { name: 'Yukon' },
    { name: 'Newfoundland and Labrador' },
    { name: 'New Brunswick' },
    { name: 'Nova Scotia' },
    { name: 'Prince Edward Island' },
  ],
  mexico: [
    { name: 'Aguascalientes' },
    { name: 'Baja California Norte' },
    { name: 'Baja California Sur' },
    { name: 'Campeche' },
    { name: 'Chiapas' },
    { name: 'Mexico City' },
    { name: 'Chihuahua' },
    { name: 'Coahuila' },
    { name: 'Colima' },
    { name: 'Durango' },
    { name: 'Guanajuato' },
    { name: 'Guerrero' },
    { name: 'Hidalgo' },
    { name: 'Jalisco' },
    { name: 'México' },
    { name: 'Michoacán' },
    { name: 'Morelos' },
    { name: 'Nayarit' },
    { name: 'Nuevo León' },
    { name: 'Oaxaca' },
    { name: 'Puebla' },
    { name: 'Querétaro' },
    { name: 'Quintana Roo' },
    { name: 'San Luis Potosí' },
    { name: 'Sinaloa' },
    { name: 'Sonora' },
    { name: 'Tabasco' },
    { name: 'Tamaulipas' },
    { name: 'Tlaxcala' },
    { name: 'Veracruz' },
    { name: 'Yucatán' },
    { name: 'Zacatecas' },
  ],
} as const satisfies Record<Country, Plate[]>

export const countryLabels: Record<Country, string> = {
  usa: 'USA',
  canada: 'Canada',
  mexico: 'Mexico',
}
